# Generated by Django 6.0.3 on 2026-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_manager_name', models.CharField(default='Store Manager', max_length=100)),
                ('store_manager_phone', models.CharField(default='9612026834', max_length=20)),
                ('store_manager_whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code e.g. 919612026834', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
