# Generated by Django 6.0.3 on 2026-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='game_shop_bg',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Game Shop Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_bg',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Home Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_bg',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Product Detail Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_bg',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Shop Page Background'),
        ),
    ]
