# Generated by Django 6.0.3 on 2026-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_game_shop_bg_sitesettings_home_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(help_text='Example: home, shop, login, dashboard', max_length=100, unique=True)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=10)),
                ('background_color', models.CharField(blank=True, help_text='Hex color, e.g. #1f2937', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/page/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Background',
                'verbose_name_plural': 'Page Backgrounds',
                'ordering': ['page_identifier'],
            },
        ),
    ]
