# Generated by Django 6.0.3 on 2026-04-03 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('DIAMOND', 'Diamonds'), ('STARLIGHT', 'Starlight Member'), ('BUNDLE', 'Bundles')], default='DIAMOND', max_length=20)),
                ('diamond_amount', models.IntegerField(blank=True, null=True)),
                ('price_coins', models.IntegerField()),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
