# Generated by Django 6.0.3 on 2026-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_seed_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_product_code',
            field=models.CharField(blank=True, help_text='Product code from Smile.one reseller catalog', max_length=50, null=True),
        ),
    ]
