# Generated by Django 6.0.3 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mlbb_user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mlbb_zone_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
