# Generated by Django 6.0.3 on 2026-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
