# Generated by Django 6.0.3 on 2026-04-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_price_coins_order_total_coins_and_more'),
        ('products', '0002_game_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mlbb_user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mlbb_zone_id',
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.game'),
        ),
        migrations.AddField(
            model_name='order',
            name='player_fields',
            field=models.JSONField(default=dict),
        ),
    ]
