# Generated by Django 6.0.3 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='smile_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='player_sid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='player_uid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='smile_product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('GATEWAY', 'Gateway')], max_length=20),
        ),
    ]
