# Generated by Django 6.0.3 on 2026-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment gateway transaction ID (ExPay orderId, Razorpay order_id, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay'), ('EXPAY', 'ExPay')], max_length=20),
        ),
    ]
