# Generated by Django 6.0.3 on 2026-04-29 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='games/banners/')),
                ('field_preset', models.CharField(choices=[('MLBB', 'User ID + Zone ID'), ('BGMI', 'Player ID only'), ('FREEFIRE', 'UID only'), ('GENSHIN', 'UID + Server'), ('HONKAI', 'UID + Server'), ('CUSTOM', 'Custom fields')], default='MLBB', max_length=20)),
                ('checkout_fields', models.JSONField(default=list)),
                ('supplier_game_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.game'),
        ),
    ]
