# Generated by Django 6.0.3 on 2026-04-29 11:19

from django.db import migrations


def seed_games(apps, schema_editor):
    Game = apps.get_model('products', 'Game')
    
    games_data = [
        {
            'name': 'Mobile Legends: Bang Bang',
            'short_name': 'MLBB',
            'slug': 'mobile-legends',
            'field_preset': 'MLBB',
            'checkout_fields': [
                {"name": "player_id", "label": "User ID", "placeholder": "e.g. 123456789", "required": True},
                {"name": "zone_id", "label": "Zone ID", "placeholder": "e.g. 1234", "required": True}
            ],
            'supplier_game_code': 'mobilelegends',
            'is_featured': True,
            'sort_order': 1,
        },
        {
            'name': 'Battlegrounds Mobile India',
            'short_name': 'BGMI',
            'slug': 'bgmi',
            'field_preset': 'BGMI',
            'checkout_fields': [
                {"name": "player_id", "label": "Player ID", "placeholder": "e.g. 5123456789", "required": True}
            ],
            'supplier_game_code': 'bgmi',
            'is_featured': True,
            'sort_order': 2,
        },
        {
            'name': 'Garena Free Fire',
            'short_name': 'FREEFIRE',
            'slug': 'free-fire',
            'field_preset': 'FREEFIRE',
            'checkout_fields': [
                {"name": "uid", "label": "Player UID", "placeholder": "e.g. 1234567890", "required": True}
            ],
            'supplier_game_code': 'freefire',
            'is_featured': True,
            'sort_order': 3,
        },
        {
            'name': 'Genshin Impact',
            'short_name': 'GENSHIN',
            'slug': 'genshin-impact',
            'field_preset': 'GENSHIN',
            'checkout_fields': [
                {"name": "uid", "label": "UID", "placeholder": "e.g. 800000000", "required": True},
                {"name": "server", "label": "Server", "placeholder": "Asia / America / Europe / TW-HK-MO", "required": True}
            ],
            'supplier_game_code': 'genshin',
            'is_featured': True,
            'sort_order': 4,
        },
        {
            'name': 'Honkai: Star Rail',
            'short_name': 'HONKAI',
            'slug': 'honkai-star-rail',
            'field_preset': 'HONKAI',
            'checkout_fields': [
                {"name": "uid", "label": "UID", "placeholder": "e.g. 600000000", "required": True},
                {"name": "server", "label": "Server", "placeholder": "Asia / America / Europe", "required": True}
            ],
            'supplier_game_code': 'honkaistarrail',
            'is_featured': True,
            'sort_order': 5,
        },
    ]
    
    for game_data in games_data:
        Game.objects.create(**game_data)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_game_model'),
    ]

    operations = [
        migrations.RunPython(seed_games),
    ]
