# Generated by Django 6.0.3 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_supplier_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='smile_product_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
